# Generated by Django 2.0.4 on 2018-09-25 06:42

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapyItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=100, null=True)),
                ('snapdeal_data', jsonfield.fields.JSONField()),
                ('paytm_data', jsonfield.fields.JSONField()),
            ],
        ),
    ]
